Repository gardener/terminal-controller-manager, pull requests merged in 2023-10, with the labels that each got.

#202 Add support for projected volume kubeconfig
  charts/terminal/charts/runtime/templates/controller-manager/deployment.yaml
  charts/terminal/values.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, needs/review, reviewed/lgtm, size/s

#203 Maintenance PR
  .github/workflows/golangci-lint.yml
  Dockerfile
  Makefile
  api/v1alpha1/terminal_types_test.go
  charts/terminal/charts/application/crd-gen/dashboard.gardener.cloud_terminals.yaml
  charts/terminal/values.yaml
  controllers/controller_suite_test.go
  controllers/serviceaccount_controller.go
  go.mod
  go.sum
  hack/golangci-lint.sh
  hack/test-integration.sh
  internal/gardenclient/client.go
  main.go
  test/common.go
  webhooks/terminal_mutating_handler.go
  webhooks/terminal_validating_handler.go
  webhooks/webhook_suite_test.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xl

#204 Revert project volume for `kube-rbac-proxy`
  charts/terminal/charts/runtime/templates/controller-manager/deployment.yaml
  charts/terminal/values.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#211 Fix component API for leader election
  api/v1alpha1/terminal_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  main.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#213 Bump kube-rbac-proxy to `v0.15.0`
  Makefile
  charts/terminal/values.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
