Repository gardener/terminal-controller-manager, pull requests merged in 2024-03, with the labels that each got.

#248 `controller-tools` version is managed via go modules
  .gitignore
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  charts/terminal/charts/application/crd-gen/dashboard.gardener.cloud_terminals.yaml
  go.mod
  go.sum
  hack/tools.go
  hack/tools.mk
  hack/tools/bin/.gitkeep
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#267 Make repo compliant
  CONTRIBUTING.md
  LICENSE
  LICENSES/Apache-2.0.txt
  LICENSES/CC-BY-4.0.txt
  NOTICE.md
  README.md
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl, area/ipcei

#246 Drop `kube-rbac-proxy` dependency, replace with `controller-runtime`s metrics authN and authZ filter
  Makefile
  README.md
  charts/terminal/charts/application/templates/controller-manager/clusterrole.yaml
  charts/terminal/charts/runtime/templates/controller-manager/clusterrole-kube-rbac-proxy.yaml
  charts/terminal/charts/runtime/templates/controller-manager/clusterrolebinding-kube-rbac-proxy.yaml
  charts/terminal/charts/runtime/templates/controller-manager/deployment.yaml
  charts/terminal/charts/runtime/templates/controller-manager/secret-kubeconfig-kube-rbac-proxy.yaml
  charts/terminal/charts/runtime/templates/controller-manager/secret-metrics-server-cert.yaml
  charts/terminal/charts/runtime/templates/controller-manager/service.yaml
  charts/terminal/values.yaml
  hack/gen-certs.sh
  hack/setup-local-dev-certs.sh
  main.go
  tls/ca-csr.json
  tls/terminal-admission-controller-tls-config.json
  tls/terminal-metrics-server-tls-config.json
Labels: needs/ok-to-test, needs/second-opinion, size/l
